
name = "DashPitViper"
uuid = "1b08a953-4be3-4667-9a23-ec6f1e78b88b"
authors = ["Leonardo C. Santos <leonardo@turquoise.health>"]
version = "0.0.2"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
